### PR TITLE
Citus fixes

### PR DESCRIPTION
**Pull request by tracyhenry**
This PR fixed the mysterious Citus serving issue by removing one line of code (i.e. using the default executor `adaptive`).

In an experiment with 512 shards (32 nodes * 16 cores) and 1B data points, indexing finished in ~1140 seconds, and the serving time was consistently around 370ms. 

Also
- cleanup of Citus/k8s scripts (more comments, move/remove out-of-place things, better logging)
- pass canvas size and rendering params to PLV8 transform functions, using Postgres native JSON cast
- set the return type of bbox functions to double arrays (was `kyrix_coords_type`), 30%~40% faster
- let transform function both accept and return JSON. A little downgrade in perf (10%?) for more concise syntax (so that the user doesn't need to specify type). 

Future work:
- spatial sharding
- implement Adam's reduce-shard-post-load strategy (to improve serving time)
- add PLV8 to single node docker (possibly merge dockerfiles)
- generalize transform func syntax, test performance
- parallel data loading (possibly using parallel COPY or pg_load)
- move Citus indexing to another indexer (to avoid confusion)

### CODE REVIEW

**Comment by asah** [comment]
Nice!

(via cellphone, random spelling ahead)

**Comment by tracyhenry** [comment]
Update:

After upgrading Citus to v8.3 and using its default adaptive executor, the serving time is improved by roughly 22% (~460ms to ~360ms) with the same setting (36 nodes * 16 cores, 1B data). Index build time remains the same.

**Comment by tracyhenry** [comment]
Update:

Returning bbox coordinates using double arrays (yes in PLV8 you can return arrays) is 30%~40% faster than using handcoded JSON-like types.

**Comment by asah** [comment]
nice!!

**Pull request merged**
